name = "DocumentationOverview"
uuid = "fd22d563-a49f-4a45-896b-231dbcd7c5a0"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PublicAPI = "e27abb06-81da-40e5-a77a-80f0fe2578fc"

[compat]
Accessors = "0.1"
PublicAPI = "0.1"
julia = "1.6"
